<?php
// Multilingual support (REQ-14): English and Arabic (right-to-left layout).

function lang(): string {
    return $_SESSION['lang'] ?? 'en';
}

// t('key', ['n' => 3]) → translated string with {n} replaced. Falls back to English, then to the key.
function t(string $key, array $vars = [], ?string $lang = null): string {
    $dict = translations();
    $lang ??= lang();
    $s = $dict[$lang][$key] ?? $dict['en'][$key] ?? ucfirst(str_replace('_', ' ', $key));
    foreach ($vars as $k => $v) $s = str_replace('{' . $k . '}', (string)$v, $s);
    return $s;
}

// Strings needed by the JavaScript files
function js_strings(): array {
    $keys = ['close', 'pw_weak', 'pw_medium', 'pw_strong', 'pw_match', 'required', 'invalid_email', 'invalid_phone', 'pw_short', 'pw_mismatch', 'link_copied', 'copy_link', 'map_offline',
             'info_about_tour', 'no_reviews_yet', 'seats_left', 'trip_full', 'trip_location'];
    return array_combine($keys, array_map('t', $keys));
}

function translations(): array {
    static $d = null;
    if ($d !== null) return $d;
    $d = [];
    $d['en'] = [
        'app_name' => 'Travel Organization',
        'welcome' => 'Welcome',
        'landing_title' => 'Discover Lebanon with local guides',
        'landing_sub' => 'Choose how you want to continue',
        'tourist_card' => 'Explore destinations and plan your next adventure.',
        'organizer_card' => 'Manage tours, bookings, and customer details efficiently.',
        'browse_without_login' => 'Browse trips without an account',
        'get_started' => 'Get started', 'watch_intro' => 'Watch the intro video', 'intro_welcome' => 'Welcome to',
        'intro_lebanon' => 'Lebanon', 'skip' => 'Skip', 'sound' => 'Sound on / off',
        'admin_login' => 'Administrator login',
        'role_tourist' => 'Tourist', 'role_organizer' => 'Travel Organizer', 'role_admin' => 'Administrator',
        'menu' => 'Menu', 'home' => 'Home', 'map' => 'Map', 'profile' => 'Profile', 'inbox' => 'Inbox',
        'search_trips' => 'Search trips', 'my_profile_bookings' => 'My profile & bookings', 'my_trips' => 'My trips',
        'create_trip' => 'Create trip', 'dashboard' => 'Dashboard', 'admin_dashboard' => 'Administrator dashboard',
        'guide_approvals' => 'Guide approvals', 'users' => 'Users', 'trips' => 'Trips', 'reviews' => 'Reviews',
        'complaints' => 'Complaints', 'reports' => 'Reports', 'system' => 'System', 'about_company' => 'About the company',
        'help_faq' => 'Help & FAQ', 'logout' => 'Log out', 'login' => 'Login', 'create_account' => 'Create Account',
        'contact_us' => 'Contact Us', 'back' => 'Back', 'back_home' => 'Back to home', 'close' => 'Close',

        // Auth
        'username_email' => 'Username (email)', 'password' => 'Password', 'forgot_password' => 'Forget password?',
        'invalid_login' => 'Invalid email or password for this account type.',
        'too_many_attempts' => 'Too many failed attempts. Please wait 5 minutes and try again.',
        'account_suspended' => 'This account is suspended. Please contact the company.',
        'account_rejected' => 'This organizer application was not approved.',
        'please_login' => 'Please log in to continue.',
        'access_denied' => 'Access denied', 'access_denied_msg' => 'Your account does not have permission to open this page.',
        'verify_code' => 'Verification', 'code_sent' => 'We sent a 6-digit code to your email address.', 'code' => 'Code',
        'verify' => 'Verify', 'wrong_code' => 'Wrong code.', 'code_expired' => 'The code expired. Please log in again.',
        'demo_mode' => 'Demo mode', 'demo_code' => 'your code is',
        'logged_out' => 'You have been logged out.',
        'forgot_help' => 'Enter your email and we will send you a link to choose a new password.',
        'send_reset' => 'Send reset link', 'reset_sent' => 'If an account exists for this email, a reset link has been sent.',
        'open_reset_link' => 'open the reset link', 'back_to_login' => 'Back to login', 'new_password' => 'New password',
        'reset_invalid' => 'This reset link is invalid or has expired.', 'pw_changed' => 'Your password has been changed.',
        'current_password' => 'Current password', 'wrong_password' => 'The current password is incorrect.',
        'change_password' => 'Change password',

        // Registration
        'tourist_registration' => 'Tourist Registration', 'organizer_registration' => 'Travel Organizer Registration',
        'full_name' => 'Full Name', 'email_address' => 'Email Address', 'phone_number' => 'Phone Number',
        'date_of_birth' => 'Date of Birth', 'nationality' => 'Nationality', 'language' => 'Language',
        'university_study' => 'University Study', 'training_licenses' => 'Professional Training or Licenses', 'skills' => 'Skills',
        'confirm_password' => 'Confirm Password', 'submit' => 'Submit', 'have_account' => 'Already have an account?',
        'ph_full_name' => 'Enter your full name', 'ph_email' => 'Enter your email address', 'ph_phone' => 'Enter your phone number',
        'ph_university' => 'Enter your university study', 'ph_training' => 'Enter your professional training or licenses',
        'ph_skills' => 'Enter your skills', 'ph_password' => 'Enter your password', 'ph_password2' => 'Confirm your password',
        'required' => 'This field is required.', 'invalid_email' => 'Please enter a valid email address.',
        'invalid_phone' => 'Please enter a valid phone number.', 'pw_short' => 'At least 8 characters.',
        'pw_rules' => 'At least 8 characters, including a letter and a number.', 'pw_mismatch' => 'Passwords do not match.',
        'err_name' => 'Please enter your name.', 'err_date' => 'Please enter a valid date.', 'err_age' => 'You must be at least {n} years old.',
        'email_taken' => 'An account already exists with this email.',
        'email_taken_hint' => 'You already have an account with this email. Log in or recover your password:',
        'org_registered' => 'Registration received! Your information was sent to the administrator for validation. You will be notified by email.',
        'tourist_registered' => 'Welcome! Your account has been created.',

        // Map / browsing
        'pin_trip' => 'Tour / place', 'pin_hotel' => 'Hotel', 'pin_restaurant' => 'Restaurant', 'pin_meeting' => 'Meeting point / guide',
        'ratings_reviews' => 'Ratings and Reviews', 'info_about_tour' => 'info about tour', 'join' => 'Join',
        'info_transport' => 'Info about transportation', 'no_transport_info' => 'Transportation details will be shared by the organizer.',
        'available_trips' => 'Available trips', 'no_trips' => 'No trips are available at the moment.',
        'map_offline' => 'The map needs an internet connection to load.',
        'seats_left' => 'Seats left', 'trip_full' => 'Trip full', 'no_reviews_yet' => 'No reviews yet',
        'destination' => 'Destination', 'search_label' => 'Destination or organizer', 'date_from' => 'From', 'date_to' => 'To', 'max_price' => 'Max price',
        'duration' => 'Duration', 'any' => 'Any', 'one_day' => '1 day', 'two_three_days' => '2–3 days', 'four_plus_days' => '4+ days',
        'sort_by' => 'Sort by', 'sort_date' => 'Date', 'sort_price_asc' => 'Price: low to high', 'sort_price_desc' => 'Price: high to low',
        'sort_rating' => 'Rating', 'search' => 'Search', 'clear_filters' => 'Clear filters', 'ph_search' => 'Destination or organizer name, e.g. Byblos or Rami',
        'n_results' => '{n} trip(s) found', 'no_trips_found' => 'No trips match your search.', 'you_may_like' => 'You may like these trips',
        'n_days' => '{n} day(s)', 'browse_trips' => 'Browse trips',

        // Trip details
        'not_found' => 'Not found', 'trip_not_public' => 'This trip is not visible to tourists',
        'schedule' => 'Schedule', 'overview_area' => 'Overview of the area', 'itinerary' => 'Itinerary', 'your_guide' => 'Your guide',
        'languages' => 'Languages', 'places_to_visit' => 'Places to visit', 'trip_price' => 'Trip price', 'person' => 'person',
        'includes' => 'Includes', 'excludes' => 'Excludes', 'view_on_map' => 'View on map', 'travel_memories' => 'Travel memories',
        'share' => 'Share', 'link_copied' => 'Link copied!', 'copy_link' => 'Copy this link:',
        'n_reviews' => '{n} reviews', 'rate_this_trip' => 'Rate this trip', 'comment' => 'Comment', 'submit_review' => 'Submit review',
        'review_moderated' => 'Reviews are published after approval by our team.',
        'review_after_trip' => 'You can rate this trip after it ends.', 'you_joined' => 'Joined',
        'trip_finished' => 'Trip finished', 'book_now' => 'Book NOW', 'edit_trip' => 'Edit trip',

        // Booking & payment
        'join_trip' => 'Join the tour', 'trip_started' => 'This trip has already started.',
        'already_joined' => 'You have already joined this trip.', 'see_alternatives' => 'See other trips', 'seats' => 'Seats',
        'payment_method' => 'Payment method', 'pay_card' => 'Credit card (Bank System)', 'pay_cash' => 'Cash',
        'total' => 'Total', 'cancel_policy' => 'Free cancellation up to {n} days before the trip. Card payments are refunded automatically.',
        'accept_policy_err' => 'Please accept the cancellation policy.', 'continue' => 'Continue',
        'err_seats' => 'Choose between 1 and 10 seats.', 'only_n_seats' => 'Only {n} seat(s) left.',
        'reserved_cash' => 'Your seats are reserved. Pay in cash to the organizer to confirm your booking.',
        'secure_payment' => 'Secure payment', 'bank_name' => 'Bank System — Secure Gateway', 'secure_conn' => 'Encrypted connection · card data is never stored',
        'card_holder' => 'Cardholder name', 'card_number' => 'Card number', 'expiry' => 'Expiry (MM/YY)', 'pay' => 'Pay',
        'card_invalid' => 'Invalid card number.', 'card_expired' => 'Invalid or expired date.', 'cvv_invalid' => 'Invalid CVV.',
        'payment_declined' => 'Payment declined by the bank. No money was taken — please retry or use another card.',
        'payment_timeout' => 'The bank did not respond in time. Your booking is still pending — please retry.',
        'payment_success' => 'Payment successful — your booking is confirmed! A confirmation email was sent.',
        'pay_later' => 'Pay later', 'cancel_booking' => 'Cancel booking', 'confirm_cancel' => 'Cancel this booking?',
        'nothing_to_pay' => 'This booking has nothing to pay.',
        'test_cards' => 'use any future expiry date and any 3-digit CVV.', 'test_cards_exp' => '✅ accepted · ❌ declined · ⏳ bank timeout',
        'receipt' => 'Receipt', 'trip' => 'Trip', 'booked_on' => 'Booked on', 'payments' => 'Payments', 'print' => 'Print',
        'pay_now' => 'Pay now', 'my_bookings' => 'My bookings',
        'cancel_too_late' => 'Confirmed bookings can only be cancelled up to {n} days before the trip.',
        'cancelled' => 'Booking cancelled.', 'cancelled_refunded' => 'Booking cancelled and your payment refunded.',

        // Reviews & photos
        'review_not_allowed' => 'You can only rate trips you attended.', 'choose_stars' => 'Please choose 1 to 5 stars.',
        'already_reviewed' => 'You already reviewed this trip.', 'review_submitted' => 'Thank you! Your review will appear after moderation.',
        'no_photos' => 'No photos yet.', 'add_photo' => 'add photo', 'photo' => 'Photo', 'caption' => 'Caption', 'ph_caption' => 'Group photo, food, views…',
        'upload' => 'Upload', 'photo_added' => 'Photo added to the travel memories.', 'photo_deleted' => 'Photo removed.',
        'confirm_delete_photo' => 'Delete this photo?', 'login_to_add_photos' => 'Log in to share your photos.',
        'only_participants' => 'Only tourists who joined this tour (and its organizer) can add photos.',
        'upload_failed' => 'The upload failed. Please try again.', 'upload_too_big' => 'The image is larger than 5 MB.',
        'upload_bad_type' => 'Only JPG, PNG, GIF or WebP images are allowed.',

        // Profile
        'name' => 'Name', 'age' => 'Age', 'email' => 'Email', 'university' => 'University', 'organizer_profile' => 'Travel Organizer Profile',
        'language_skills' => 'Language Skills', 'ph_language_skills' => 'List your language skills',
        'training_license' => 'Professional Training or License', 'rating' => 'Rating', 'tours_made' => 'Tours Made',
        'no_trips_yet' => 'No trips yet.', 'save_changes' => 'Save changes', 'profile_saved' => 'Profile saved.',
        'tours_joined' => 'Tours You Have Joined', 'no_bookings' => 'You have not joined any tour yet.', 'rate' => 'Rate',
        'cancel' => 'Cancel', 'trip_cancelled' => 'Trip cancelled',

        // Complaints & inbox
        'submit_complaint' => 'Submit a complaint', 'related_trip' => 'Related trip', 'none' => '— None —', 'subject' => 'Subject',
        'message' => 'Message', 'send' => 'Send', 'err_message_short' => 'Please write at least 10 characters.',
        'complaint_sent' => 'Your complaint was sent. An administrator will reply soon.', 'my_complaints' => 'My complaints',
        'no_complaints' => 'You have not submitted any complaint.', 'admin_response' => 'Administrator response',
        'mark_all_read' => 'Mark all as read', 'inbox_hint' => 'Emails and notifications sent to you by the system.',
        'inbox_empty' => 'Your inbox is empty.', 'address' => 'Address', 'message_sent' => 'Thank you! Your message has been sent.',

        // Organizer
        'pending_notice' => 'Your account is waiting for validation by an administrator. You will be able to create trips once it is approved.',
        'pending_cannot_publish' => 'Your account must be approved before you can create or publish trips.',
        'upcoming' => 'Upcoming', 'revenue_paid' => 'Revenue (paid)', 'status' => 'Status', 'price' => 'Price', 'discount' => 'Discount',
        'actions' => 'Actions', 'apply' => 'Apply', 'edit' => 'Edit', 'bookings' => 'Bookings', 'publish' => 'Publish',
        'unpublish' => 'Unpublish', 'delete' => 'Delete',
        'discount_rule' => 'Discounts must be between 0% and {n}% of the base price.', 'discount_applied' => 'Discount of {n}% applied.',
        'trip_published' => 'Trip published.', 'trip_unpublished' => 'Trip moved back to draft.',
        'has_bookings_unpublish' => 'A trip with active bookings cannot be unpublished.',
        'delete_blocked' => 'This trip has {n} active booking(s) and cannot be deleted. An administrator has been asked to review it.',
        'trip_deleted' => 'Trip deleted.', 'delete_rule' => 'Trips with active bookings can only be deleted by an administrator.',
        'confirm_delete_trip' => 'Delete this trip permanently?',
        'trip_details' => 'Trip details', 'title' => 'Title', 'start_date' => 'Start date', 'end_date' => 'End date',
        'price_per_person' => 'Price per person', 'capacity' => 'Capacity (seats)', 'trip_language' => 'Tour language',
        'ph_includes' => 'Transportation, guide…', 'ph_excludes' => 'Lunch…', 'ph_transport' => 'Meeting point, departure time, vehicle…',
        'cover_photo' => 'Cover photo', 'location' => 'Location on the map', 'map_pick_help' => 'Click on the map to set the location of:',
        'trip_location' => 'the trip', 'add_stop' => 'Add place', 'stops_help' => 'Places, hotels, restaurants and meeting points appear as pins on the tourist map.',
        'type' => 'Type', 'entrance_info' => 'Entrance info', 'ph_entrance' => 'Free entrance', 'description' => 'Description',
        'pick_on_map' => 'Pick on map', 'remove' => 'Remove', 'fix_errors' => 'Please correct the highlighted fields.',
        'err_past_date' => 'The date cannot be in the past.', 'err_end_before_start' => 'The end date must be after the start date.',
        'err_price' => 'Enter a valid price.', 'err_capacity' => 'Capacity must be at least 1.',
        'err_capacity_booked' => '{n} seats are already booked; capacity cannot be lower.', 'err_location' => 'Choose a valid location on the map.',
        'already_booked' => '{n} seat(s) already booked.', 'trip_updated' => 'Trip updated.', 'trip_created' => 'Trip created.',
        'no_bookings_trip' => 'No bookings yet for this trip.', 'payment' => 'Payment', 'cash_received' => 'Cash received',
        'confirm_cash' => 'Confirm that you received the cash payment?', 'cash_recorded' => 'Cash payment recorded — the booking is confirmed.',

        // Admin
        'pending_guides' => 'Guides to validate', 'pending_reviews' => 'Reviews to moderate', 'open_complaints' => 'Open complaints',
        'unread_messages' => 'Unread messages', 'tourists' => 'Tourists', 'organizers' => 'Organizers', 'active_trips' => 'Active trips',
        'bookings_30d' => 'Bookings (30 days)', 'recent_activity' => 'Recent activity', 'view_all' => 'View all', 'date' => 'Date',
        'user' => 'User', 'action' => 'Action', 'details' => 'Details', 'maintenance_on' => 'Maintenance mode ON',
        'registered' => 'Registered', 'note' => 'Note', 'ph_admin_note' => 'Optional note / reason / information requested…',
        'approve' => 'Approve', 'reject' => 'Reject', 'request_info' => 'Request more info', 'view_profile' => 'View profile',
        'guide_approved' => 'Organizer approved and notified by email.', 'guide_rejected' => 'Organizer rejected and notified by email.',
        'info_requested' => 'Information request sent by email.', 'confirm_reject' => 'Reject this application?', 'nothing_here' => 'Nothing here.',
        'add_admin' => 'Add administrator', 'all' => 'All', 'ph_user_search' => 'Name, email or phone', 'role' => 'Role', 'activity' => 'Activity',
        'reactivate' => 'Reactivate', 'suspend' => 'Suspend', 'reason' => 'Reason', 'you' => 'You', 'confirm_action' => 'Are you sure?',
        'cannot_self' => 'You cannot do that to your own account.', 'user_suspended' => 'Account suspended.',
        'user_reactivated' => 'Account reactivated.', 'user_deleted' => 'Account deleted.', 'admin_created' => 'Administrator account created.',
        'cancel_trip' => 'Cancel trip', 'confirm_cancel_trip' => 'Cancel this trip? All bookings will be cancelled and refunded.',
        'override_delete' => 'Override & delete', 'confirm_override' => 'ADMIN OVERRIDE: this trip has {n} booked seat(s). They will be cancelled and refunded. Delete anyway?',
        'trip_cancelled_ok' => 'Trip cancelled; tourists notified and refunded.', 'saved' => 'Saved.',
        'photos' => 'Photos', 'hide' => 'Hide', 'show' => 'Show',
        'response_required' => 'Please write a response.', 'ph_response' => 'Write your response to the sender…',
        'respond_resolve' => 'Respond & resolve', 'reply_only' => 'Reply (keep open)', 'escalate' => 'Escalate',
        'print_pdf' => 'Print / PDF', 'generate' => 'Generate', 'period' => 'Period', 'avg_rating' => 'Average rating',
        'new_users' => 'New users', 'logins' => 'Logins', 'revenue_by_trip' => 'Revenue by trip (confirmed)',
        'bookings_per_month' => 'Confirmed bookings per month', 'amount' => 'Amount', 'ratings_by_trip' => 'Ratings by trip',
        'export_csv' => 'Export to CSV', 'report_history' => 'Generated reports',
        'exp_bookings' => 'Bookings', 'exp_payments' => 'Payments', 'exp_complaints' => 'Complaints', 'exp_ratings' => 'Ratings', 'exp_users' => 'Users',
        'maintenance' => 'Maintenance', 'maintenance_msg' => 'The system is under maintenance. Please come back later.',
        'maintenance_help' => 'While maintenance is on, only administrators can use the system; everyone else sees a notice.',
        'maintenance_off' => 'Maintenance finished — the system is back online.', 'online' => 'Online',
        'notice_message' => 'Notice message', 'start_maintenance' => 'Start maintenance', 'end_maintenance' => 'End maintenance',
        'company_info' => 'Company information', 'save' => 'Save', 'contact_messages' => 'Contact messages',
        'audit_log' => 'Audit log', 'email_log' => 'Outgoing emails',
        'email_log_help' => 'Every email the system sends is recorded here and in the recipient\'s Inbox.',

        // Profile (Instagram style) & favorites
        'edit_profile' => 'Edit profile', 'settings' => 'Settings', 'change_photo' => 'Change profile photo',
        'stat_trips' => 'trips', 'stat_reviews' => 'reviews', 'favorites' => 'Favorites',
        'member_since' => 'Member since', 'tap_to_add_photo' => 'Tap the circle to add a profile photo (optional).',
        'no_favorites' => 'No favorites yet — tap ♡ on any trip to save it here.',
        'add_favorite' => 'Add to favorites', 'remove_favorite' => 'Remove from favorites',
        'saved_to_favorites' => 'Saved to your favorites ♥', 'removed_from_favorites' => 'Removed from favorites',
        'photo_updated' => 'Profile photo updated.', 'photo_removed' => 'Profile photo removed.',
        'profile_photo' => 'Profile photo', 'profile_photo_hint' => 'Tap your picture on the profile to change it.',
        'remove_photo' => 'Remove photo', 'security' => 'Password & security', 'security_hint' => 'Change your password',
        'show_password' => 'Show password', 'update_password' => 'Update password',
        'rule_len' => '8+ characters', 'rule_letter' => 'a letter', 'rule_digit' => 'a number',
        'pw_weak' => 'Weak', 'pw_medium' => 'Medium', 'pw_strong' => 'Strong', 'pw_match' => 'Passwords match',
        'demo_restricted' => 'This is a public demo account: it can only view and change demo data.',
        'demo_no_reset' => 'Demo accounts\' passwords cannot be reset. Use the password shown in the README.',
        'reset_unavailable' => 'Password reset by email is not available yet. Please contact the company.',
        'code_not_sent' => 'The login code could not be sent by email. Please try again later.',
        'demo_domain_reserved' => 'This email domain is reserved for demo accounts. Please use your own email.',
        'real_card_warning' => 'Simulated payment gateway: no real money is charged. Do not enter a real card — use the test card 4242 4242 4242 4242.',
        'demo_banner' => 'You are using a public demo account: you only see demo data, and changes to the account are disabled.',
        'follow' => 'Follow', 'following' => 'Following', 'followers' => 'followers',
        'now_following' => 'You follow {name} — you will be notified of their new trips.', 'unfollowed' => 'You unfollowed {name}.',
        'no_following' => 'You do not follow any travel organizer yet. Follow one to see their newest trips here.',
        'find_organizers' => 'Find organizers', 'new_from_following' => 'Newest trips from organizers you follow',
        'no_new_trips' => 'No upcoming trips from them right now.', 'new' => 'NEW',
        'about_organizer' => 'About', 'about_tab' => 'About', 'verified_hint' => 'Verified by the company',
        'n_upcoming' => '{n} upcoming trip(s)', 'trips_summary' => '{n} published · {u} upcoming',
        'private' => 'only you', 'contact' => 'Contact', 'contact_via_company' => 'Contact the organizer through the company',
        'organizers_found' => 'Travel organizers',

        // Status labels
        'st_active' => 'Active', 'st_pending' => 'Pending', 'st_rejected' => 'Rejected', 'st_suspended' => 'Suspended',
        'st_confirmed' => 'Confirmed', 'st_cancelled' => 'Cancelled', 'st_paid' => 'Paid', 'st_failed' => 'Failed',
        'st_refunded' => 'Refunded', 'st_approved' => 'Approved', 'st_hidden' => 'Hidden', 'st_published' => 'Published',
        'st_draft' => 'Draft', 'st_open' => 'Open', 'st_resolved' => 'Resolved', 'st_escalated' => 'Escalated', 'st_visible' => 'Visible',

        // Help / FAQ
        'help_tourists' => 'For tourists', 'help_organizers' => 'For travel organizers', 'help_general' => 'General',
        'help_more' => 'Still need help?',
        'faq_t1_q' => 'How do I join a tour?', 'faq_t1_a' => "Open the Map (home icon), tap a green pin and press \"Join\" — or open a trip and press \"Book NOW\". Enter your name, phone number and language, choose the number of seats and the payment method.",
        'faq_t2_q' => 'Which payment methods are accepted?', 'faq_t2_a' => "Credit card (processed securely by the Bank System — your card number is never stored) or cash. Cash reservations are confirmed once the organizer records your payment.",
        'faq_t3_q' => 'Can I cancel a booking?', 'faq_t3_a' => "Yes. Open Profile › Tours You Have Joined and press Cancel. Confirmed bookings can be cancelled up to 2 days before the trip; card payments are refunded automatically.",
        'faq_t4_q' => 'How do I rate a trip?', 'faq_t4_a' => "After the trip ends, open it and choose 1 to 5 stars with an optional comment. Reviews are published after moderation.",
        'faq_t5_q' => 'How do I share photos?', 'faq_t5_a' => "Open the trip › Travel memories and press \"add photo\". Only participants of the tour can add photos.",
        'faq_t6_q' => 'How do I move between pages on my phone?', 'faq_t6_a' => "Use the bottom bar (Profile, Inbox, Home, Search) or simply swipe left or right.",
        'faq_o1_q' => 'How do I become a travel organizer?', 'faq_o1_a' => "Register as Travel Organizer with your university study, training/licenses and skills. An administrator validates your information and you are notified by email.",
        'faq_o2_q' => 'How do I create a trip?', 'faq_o2_a' => "My trips › Create trip. Fill in the details, click on the map to set the location and add the places, hotels and restaurants of the tour.",
        'faq_o3_q' => 'Are there rules for discounts?', 'faq_o3_a' => "Discounts can go from 0% to 50% of the base price.",
        'faq_o4_q' => 'Can I delete a trip?', 'faq_o4_a' => "Yes, if it has no active bookings. Otherwise an administrator must review and override the deletion.",
        'faq_g1_q' => 'Is my data safe?', 'faq_g1_a' => "Passwords are hashed, access is role-based, administrator logins require a one-time code and all administrative actions are logged.",
        'faq_g2_q' => 'Can I use the app in Arabic?', 'faq_g2_a' => "Yes — use the عربي / EN button at the top of every page.",
        'faq_g3_q' => 'I forgot my password', 'faq_g3_a' => "On the login page press \"Forget password?\" and follow the link sent to your email.",
    ];

    $d['ar'] = [
        'app_name' => 'منظمة السفر',
        'welcome' => 'أهلاً وسهلاً',
        'landing_title' => 'اكتشف لبنان مع مرشدين محليين',
        'landing_sub' => 'اختر طريقة المتابعة',
        'tourist_card' => 'استكشف الوجهات وخطط لمغامرتك القادمة.',
        'organizer_card' => 'أدر الجولات والحجوزات وبيانات العملاء بكفاءة.',
        'browse_without_login' => 'تصفح الرحلات بدون حساب',
        'get_started' => 'ابدأ الآن', 'watch_intro' => 'شاهد الفيديو التعريفي', 'intro_welcome' => 'أهلاً بكم في',
        'intro_lebanon' => 'لبنان', 'skip' => 'تخطي', 'sound' => 'تشغيل / إيقاف الصوت',
        'admin_login' => 'دخول المسؤول',
        'role_tourist' => 'سائح', 'role_organizer' => 'منظم رحلات', 'role_admin' => 'مسؤول',
        'menu' => 'القائمة', 'home' => 'الرئيسية', 'map' => 'الخريطة', 'profile' => 'الملف الشخصي', 'inbox' => 'البريد',
        'search_trips' => 'البحث عن رحلات', 'my_profile_bookings' => 'ملفي وحجوزاتي', 'my_trips' => 'رحلاتي',
        'create_trip' => 'إنشاء رحلة', 'dashboard' => 'لوحة التحكم', 'admin_dashboard' => 'لوحة تحكم المسؤول',
        'guide_approvals' => 'اعتماد المرشدين', 'users' => 'المستخدمون', 'trips' => 'الرحلات', 'reviews' => 'التقييمات',
        'complaints' => 'الشكاوى', 'reports' => 'التقارير', 'system' => 'النظام', 'about_company' => 'عن الشركة',
        'help_faq' => 'المساعدة والأسئلة', 'logout' => 'تسجيل الخروج', 'login' => 'تسجيل الدخول', 'create_account' => 'إنشاء حساب',
        'contact_us' => 'اتصل بنا', 'back' => 'رجوع', 'back_home' => 'العودة للرئيسية', 'close' => 'إغلاق',

        'username_email' => 'اسم المستخدم (البريد الإلكتروني)', 'password' => 'كلمة المرور', 'forgot_password' => 'نسيت كلمة المرور؟',
        'invalid_login' => 'البريد الإلكتروني أو كلمة المرور غير صحيحة لهذا النوع من الحسابات.',
        'too_many_attempts' => 'محاولات فاشلة كثيرة. انتظر 5 دقائق ثم حاول مجدداً.',
        'account_suspended' => 'هذا الحساب موقوف. يرجى التواصل مع الشركة.',
        'account_rejected' => 'لم تتم الموافقة على طلب المنظم هذا.',
        'please_login' => 'يرجى تسجيل الدخول للمتابعة.',
        'access_denied' => 'غير مسموح', 'access_denied_msg' => 'ليس لحسابك صلاحية فتح هذه الصفحة.',
        'verify_code' => 'التحقق', 'code_sent' => 'أرسلنا رمزاً من 6 أرقام إلى بريدك الإلكتروني.', 'code' => 'الرمز',
        'verify' => 'تحقق', 'wrong_code' => 'رمز خاطئ.', 'code_expired' => 'انتهت صلاحية الرمز. سجّل الدخول مجدداً.',
        'demo_mode' => 'وضع العرض', 'demo_code' => 'رمزك هو',
        'logged_out' => 'تم تسجيل خروجك.',
        'forgot_help' => 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.',
        'send_reset' => 'إرسال رابط الاستعادة', 'reset_sent' => 'إذا كان هناك حساب بهذا البريد، فقد أُرسل رابط الاستعادة.',
        'open_reset_link' => 'افتح رابط الاستعادة', 'back_to_login' => 'العودة لتسجيل الدخول', 'new_password' => 'كلمة مرور جديدة',
        'reset_invalid' => 'رابط الاستعادة غير صالح أو منتهي الصلاحية.', 'pw_changed' => 'تم تغيير كلمة المرور.',
        'current_password' => 'كلمة المرور الحالية', 'wrong_password' => 'كلمة المرور الحالية غير صحيحة.',
        'change_password' => 'تغيير كلمة المرور',

        'tourist_registration' => 'تسجيل سائح', 'organizer_registration' => 'تسجيل منظم رحلات',
        'full_name' => 'الاسم الكامل', 'email_address' => 'البريد الإلكتروني', 'phone_number' => 'رقم الهاتف',
        'date_of_birth' => 'تاريخ الميلاد', 'nationality' => 'الجنسية', 'language' => 'اللغة',
        'university_study' => 'الدراسة الجامعية', 'training_licenses' => 'التدريب المهني أو الرخص', 'skills' => 'المهارات',
        'confirm_password' => 'تأكيد كلمة المرور', 'submit' => 'إرسال', 'have_account' => 'لديك حساب؟',
        'ph_full_name' => 'أدخل اسمك الكامل', 'ph_email' => 'أدخل بريدك الإلكتروني', 'ph_phone' => 'أدخل رقم هاتفك',
        'ph_university' => 'أدخل دراستك الجامعية', 'ph_training' => 'أدخل تدريبك المهني أو رخصك',
        'ph_skills' => 'أدخل مهاراتك', 'ph_password' => 'أدخل كلمة المرور', 'ph_password2' => 'أكّد كلمة المرور',
        'required' => 'هذا الحقل مطلوب.', 'invalid_email' => 'يرجى إدخال بريد إلكتروني صحيح.',
        'invalid_phone' => 'يرجى إدخال رقم هاتف صحيح.', 'pw_short' => '8 أحرف على الأقل.',
        'pw_rules' => '8 أحرف على الأقل، تتضمن حرفاً ورقماً.', 'pw_mismatch' => 'كلمتا المرور غير متطابقتين.',
        'err_name' => 'يرجى إدخال الاسم.', 'err_date' => 'يرجى إدخال تاريخ صحيح.', 'err_age' => 'يجب أن يكون عمرك {n} سنة على الأقل.',
        'email_taken' => 'يوجد حساب بهذا البريد الإلكتروني.',
        'email_taken_hint' => 'لديك حساب بهذا البريد. سجّل الدخول أو استعد كلمة المرور:',
        'org_registered' => 'تم استلام طلبك! أُرسلت معلوماتك إلى المسؤول للتحقق منها، وسيصلك بريد إلكتروني.',
        'tourist_registered' => 'أهلاً بك! تم إنشاء حسابك.',

        'pin_trip' => 'جولة / مكان', 'pin_hotel' => 'فندق', 'pin_restaurant' => 'مطعم', 'pin_meeting' => 'نقطة لقاء / المرشد',
        'ratings_reviews' => 'التقييمات والمراجعات', 'info_about_tour' => 'معلومات عن الجولة', 'join' => 'انضم',
        'info_transport' => 'معلومات عن النقل', 'no_transport_info' => 'سيشارك المنظم تفاصيل النقل.',
        'available_trips' => 'الرحلات المتاحة', 'no_trips' => 'لا توجد رحلات متاحة حالياً.',
        'map_offline' => 'تحتاج الخريطة إلى اتصال بالإنترنت.',
        'seats_left' => 'المقاعد المتبقية', 'trip_full' => 'الرحلة ممتلئة', 'no_reviews_yet' => 'لا توجد تقييمات بعد',
        'destination' => 'الوجهة', 'search_label' => 'الوجهة أو المنظم', 'date_from' => 'من', 'date_to' => 'إلى', 'max_price' => 'أقصى سعر',
        'duration' => 'المدة', 'any' => 'الكل', 'one_day' => 'يوم واحد', 'two_three_days' => '2–3 أيام', 'four_plus_days' => '4 أيام أو أكثر',
        'sort_by' => 'ترتيب حسب', 'sort_date' => 'التاريخ', 'sort_price_asc' => 'السعر: من الأقل', 'sort_price_desc' => 'السعر: من الأعلى',
        'sort_rating' => 'التقييم', 'search' => 'بحث', 'clear_filters' => 'مسح الفلاتر', 'ph_search' => 'الوجهة أو اسم المنظم، مثلاً جبيل أو رامي',
        'n_results' => 'تم العثور على {n} رحلة', 'no_trips_found' => 'لا توجد رحلات تطابق بحثك.', 'you_may_like' => 'رحلات قد تعجبك',
        'n_days' => '{n} يوم', 'browse_trips' => 'تصفح الرحلات',

        'not_found' => 'غير موجود', 'trip_not_public' => 'هذه الرحلة غير ظاهرة للسياح',
        'schedule' => 'الموعد', 'overview_area' => 'نظرة عامة على المنطقة', 'itinerary' => 'برنامج الرحلة', 'your_guide' => 'مرشدك',
        'languages' => 'اللغات', 'places_to_visit' => 'أماكن الزيارة', 'trip_price' => 'سعر الرحلة', 'person' => 'شخص',
        'includes' => 'يشمل', 'excludes' => 'لا يشمل', 'view_on_map' => 'عرض على الخريطة', 'travel_memories' => 'ذكريات السفر',
        'share' => 'مشاركة', 'link_copied' => 'تم نسخ الرابط!', 'copy_link' => 'انسخ هذا الرابط:',
        'n_reviews' => '{n} تقييم', 'rate_this_trip' => 'قيّم هذه الرحلة', 'comment' => 'تعليق', 'submit_review' => 'إرسال التقييم',
        'review_moderated' => 'تُنشر التقييمات بعد موافقة فريقنا.',
        'review_after_trip' => 'يمكنك تقييم الرحلة بعد انتهائها.', 'you_joined' => 'منضم',
        'trip_finished' => 'انتهت الرحلة', 'book_now' => 'احجز الآن', 'edit_trip' => 'تعديل الرحلة',

        'join_trip' => 'الانضمام إلى الجولة', 'trip_started' => 'بدأت هذه الرحلة بالفعل.',
        'already_joined' => 'أنت منضم إلى هذه الرحلة بالفعل.', 'see_alternatives' => 'رحلات أخرى', 'seats' => 'المقاعد',
        'payment_method' => 'طريقة الدفع', 'pay_card' => 'بطاقة ائتمان (النظام المصرفي)', 'pay_cash' => 'نقداً',
        'total' => 'المجموع', 'cancel_policy' => 'إلغاء مجاني حتى {n} أيام قبل الرحلة. تُسترد مدفوعات البطاقة تلقائياً.',
        'accept_policy_err' => 'يرجى قبول سياسة الإلغاء.', 'continue' => 'متابعة',
        'err_seats' => 'اختر بين 1 و 10 مقاعد.', 'only_n_seats' => 'بقي {n} مقعد فقط.',
        'reserved_cash' => 'تم حجز مقاعدك. ادفع نقداً للمنظم لتأكيد الحجز.',
        'secure_payment' => 'دفع آمن', 'bank_name' => 'النظام المصرفي — بوابة آمنة', 'secure_conn' => 'اتصال مشفّر · لا يتم حفظ بيانات البطاقة',
        'card_holder' => 'اسم حامل البطاقة', 'card_number' => 'رقم البطاقة', 'expiry' => 'تاريخ الانتهاء (MM/YY)', 'pay' => 'ادفع',
        'card_invalid' => 'رقم بطاقة غير صالح.', 'card_expired' => 'تاريخ غير صالح أو منتهٍ.', 'cvv_invalid' => 'رمز CVV غير صالح.',
        'payment_declined' => 'رفض البنك الدفع. لم يُخصم أي مبلغ — أعد المحاولة أو استخدم بطاقة أخرى.',
        'payment_timeout' => 'لم يستجب البنك في الوقت المحدد. حجزك ما زال معلقاً — أعد المحاولة.',
        'payment_success' => 'تم الدفع بنجاح — تم تأكيد حجزك! أُرسل بريد تأكيد.',
        'pay_later' => 'الدفع لاحقاً', 'cancel_booking' => 'إلغاء الحجز', 'confirm_cancel' => 'هل تريد إلغاء هذا الحجز؟',
        'nothing_to_pay' => 'لا يوجد مبلغ مستحق لهذا الحجز.',
        'test_cards' => 'استخدم أي تاريخ انتهاء مستقبلي وأي CVV من 3 أرقام.', 'test_cards_exp' => '✅ مقبولة · ❌ مرفوضة · ⏳ انتهاء مهلة البنك',
        'receipt' => 'إيصال', 'trip' => 'الرحلة', 'booked_on' => 'تاريخ الحجز', 'payments' => 'المدفوعات', 'print' => 'طباعة',
        'pay_now' => 'ادفع الآن', 'my_bookings' => 'حجوزاتي',
        'cancel_too_late' => 'يمكن إلغاء الحجوزات المؤكدة حتى {n} أيام قبل الرحلة فقط.',
        'cancelled' => 'تم إلغاء الحجز.', 'cancelled_refunded' => 'تم إلغاء الحجز واسترداد المبلغ.',

        'review_not_allowed' => 'يمكنك تقييم الرحلات التي شاركت فيها فقط.', 'choose_stars' => 'يرجى اختيار من 1 إلى 5 نجوم.',
        'already_reviewed' => 'لقد قيّمت هذه الرحلة بالفعل.', 'review_submitted' => 'شكراً! سيظهر تقييمك بعد المراجعة.',
        'no_photos' => 'لا توجد صور بعد.', 'add_photo' => 'إضافة صورة', 'photo' => 'صورة', 'caption' => 'وصف', 'ph_caption' => 'صورة جماعية، طعام، مناظر…',
        'upload' => 'رفع', 'photo_added' => 'أُضيفت الصورة إلى ذكريات السفر.', 'photo_deleted' => 'تم حذف الصورة.',
        'confirm_delete_photo' => 'حذف هذه الصورة؟', 'login_to_add_photos' => 'سجّل الدخول لمشاركة صورك.',
        'only_participants' => 'يمكن فقط للسياح المشاركين في الجولة (ومنظمها) إضافة صور.',
        'upload_failed' => 'فشل الرفع. حاول مجدداً.', 'upload_too_big' => 'حجم الصورة أكبر من 5 ميغابايت.',
        'upload_bad_type' => 'يُسمح فقط بصور JPG أو PNG أو GIF أو WebP.',

        'name' => 'الاسم', 'age' => 'العمر', 'email' => 'البريد الإلكتروني', 'university' => 'الجامعة', 'organizer_profile' => 'ملف منظم الرحلات',
        'language_skills' => 'المهارات اللغوية', 'ph_language_skills' => 'اذكر اللغات التي تتقنها',
        'training_license' => 'التدريب المهني أو الرخصة', 'rating' => 'التقييم', 'tours_made' => 'الجولات المنظمة',
        'no_trips_yet' => 'لا توجد رحلات بعد.', 'save_changes' => 'حفظ التغييرات', 'profile_saved' => 'تم حفظ الملف الشخصي.',
        'tours_joined' => 'الجولات التي انضممت إليها', 'no_bookings' => 'لم تنضم إلى أي جولة بعد.', 'rate' => 'قيّم',
        'cancel' => 'إلغاء', 'trip_cancelled' => 'الرحلة ملغاة',

        'submit_complaint' => 'تقديم شكوى', 'related_trip' => 'الرحلة المعنية', 'none' => '— لا شيء —', 'subject' => 'الموضوع',
        'message' => 'الرسالة', 'send' => 'إرسال', 'err_message_short' => 'يرجى كتابة 10 أحرف على الأقل.',
        'complaint_sent' => 'تم إرسال شكواك. سيرد عليك أحد المسؤولين قريباً.', 'my_complaints' => 'شكاواي',
        'no_complaints' => 'لم تقدّم أي شكوى.', 'admin_response' => 'رد المسؤول',
        'mark_all_read' => 'تحديد الكل كمقروء', 'inbox_hint' => 'الرسائل والإشعارات التي أرسلها النظام إليك.',
        'inbox_empty' => 'صندوق البريد فارغ.', 'address' => 'العنوان', 'message_sent' => 'شكراً! تم إرسال رسالتك.',

        'pending_notice' => 'حسابك بانتظار التحقق من قبل المسؤول. ستتمكن من إنشاء الرحلات بعد الموافقة.',
        'pending_cannot_publish' => 'يجب الموافقة على حسابك قبل إنشاء أو نشر الرحلات.',
        'upcoming' => 'القادمة', 'revenue_paid' => 'الإيرادات (المدفوعة)', 'status' => 'الحالة', 'price' => 'السعر', 'discount' => 'الخصم',
        'actions' => 'إجراءات', 'apply' => 'تطبيق', 'edit' => 'تعديل', 'bookings' => 'الحجوزات', 'publish' => 'نشر',
        'unpublish' => 'إلغاء النشر', 'delete' => 'حذف',
        'discount_rule' => 'يجب أن يكون الخصم بين 0% و {n}% من السعر الأساسي.', 'discount_applied' => 'تم تطبيق خصم {n}%.',
        'trip_published' => 'تم نشر الرحلة.', 'trip_unpublished' => 'أُعيدت الرحلة إلى المسودة.',
        'has_bookings_unpublish' => 'لا يمكن إلغاء نشر رحلة لديها حجوزات نشطة.',
        'delete_blocked' => 'لدى هذه الرحلة {n} حجز نشط ولا يمكن حذفها. طُلب من المسؤول مراجعتها.',
        'trip_deleted' => 'تم حذف الرحلة.', 'delete_rule' => 'لا يحذف الرحلات ذات الحجوزات النشطة إلا المسؤول.',
        'confirm_delete_trip' => 'حذف هذه الرحلة نهائياً؟',
        'trip_details' => 'تفاصيل الرحلة', 'title' => 'العنوان', 'start_date' => 'تاريخ البدء', 'end_date' => 'تاريخ الانتهاء',
        'price_per_person' => 'السعر للشخص', 'capacity' => 'السعة (المقاعد)', 'trip_language' => 'لغة الجولة',
        'ph_includes' => 'النقل، المرشد…', 'ph_excludes' => 'الغداء…', 'ph_transport' => 'نقطة اللقاء، وقت الانطلاق، المركبة…',
        'cover_photo' => 'صورة الغلاف', 'location' => 'الموقع على الخريطة', 'map_pick_help' => 'انقر على الخريطة لتحديد موقع:',
        'trip_location' => 'الرحلة', 'add_stop' => 'إضافة مكان', 'stops_help' => 'تظهر الأماكن والفنادق والمطاعم ونقاط اللقاء كدبابيس على خريطة السائح.',
        'type' => 'النوع', 'entrance_info' => 'معلومات الدخول', 'ph_entrance' => 'دخول مجاني', 'description' => 'الوصف',
        'pick_on_map' => 'اختر على الخريطة', 'remove' => 'إزالة', 'fix_errors' => 'يرجى تصحيح الحقول المحددة.',
        'err_past_date' => 'لا يمكن أن يكون التاريخ في الماضي.', 'err_end_before_start' => 'يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء.',
        'err_price' => 'أدخل سعراً صحيحاً.', 'err_capacity' => 'يجب أن تكون السعة 1 على الأقل.',
        'err_capacity_booked' => 'تم حجز {n} مقعد؛ لا يمكن أن تكون السعة أقل.', 'err_location' => 'اختر موقعاً صحيحاً على الخريطة.',
        'already_booked' => 'تم حجز {n} مقعد.', 'trip_updated' => 'تم تحديث الرحلة.', 'trip_created' => 'تم إنشاء الرحلة.',
        'no_bookings_trip' => 'لا توجد حجوزات لهذه الرحلة بعد.', 'payment' => 'الدفع', 'cash_received' => 'تم استلام النقد',
        'confirm_cash' => 'هل تؤكد استلام الدفعة النقدية؟', 'cash_recorded' => 'تم تسجيل الدفع النقدي — الحجز مؤكد.',

        'pending_guides' => 'مرشدون بانتظار التحقق', 'pending_reviews' => 'تقييمات بانتظار المراجعة', 'open_complaints' => 'شكاوى مفتوحة',
        'unread_messages' => 'رسائل غير مقروءة', 'tourists' => 'السياح', 'organizers' => 'المنظمون', 'active_trips' => 'الرحلات النشطة',
        'bookings_30d' => 'الحجوزات (30 يوماً)', 'recent_activity' => 'النشاط الأخير', 'view_all' => 'عرض الكل', 'date' => 'التاريخ',
        'user' => 'المستخدم', 'action' => 'الإجراء', 'details' => 'التفاصيل', 'maintenance_on' => 'وضع الصيانة مفعّل',
        'registered' => 'مسجّل منذ', 'note' => 'ملاحظة', 'ph_admin_note' => 'ملاحظة / سبب / معلومات مطلوبة (اختياري)…',
        'approve' => 'موافقة', 'reject' => 'رفض', 'request_info' => 'طلب معلومات إضافية', 'view_profile' => 'عرض الملف',
        'guide_approved' => 'تمت الموافقة على المنظم وإبلاغه بالبريد.', 'guide_rejected' => 'تم رفض المنظم وإبلاغه بالبريد.',
        'info_requested' => 'تم إرسال طلب المعلومات بالبريد.', 'confirm_reject' => 'رفض هذا الطلب؟', 'nothing_here' => 'لا يوجد شيء هنا.',
        'add_admin' => 'إضافة مسؤول', 'all' => 'الكل', 'ph_user_search' => 'الاسم أو البريد أو الهاتف', 'role' => 'الدور', 'activity' => 'النشاط',
        'reactivate' => 'إعادة التفعيل', 'suspend' => 'إيقاف', 'reason' => 'السبب', 'you' => 'أنت', 'confirm_action' => 'هل أنت متأكد؟',
        'cannot_self' => 'لا يمكنك القيام بذلك على حسابك.', 'user_suspended' => 'تم إيقاف الحساب.',
        'user_reactivated' => 'تمت إعادة تفعيل الحساب.', 'user_deleted' => 'تم حذف الحساب.', 'admin_created' => 'تم إنشاء حساب المسؤول.',
        'cancel_trip' => 'إلغاء الرحلة', 'confirm_cancel_trip' => 'إلغاء هذه الرحلة؟ ستُلغى جميع الحجوزات وتُسترد المبالغ.',
        'override_delete' => 'تجاوز وحذف', 'confirm_override' => 'تجاوز المسؤول: لدى الرحلة {n} مقعد محجوز. ستُلغى وتُسترد. هل تريد الحذف؟',
        'trip_cancelled_ok' => 'أُلغيت الرحلة؛ تم إبلاغ السياح واسترداد المبالغ.', 'saved' => 'تم الحفظ.',
        'photos' => 'الصور', 'hide' => 'إخفاء', 'show' => 'إظهار',
        'response_required' => 'يرجى كتابة رد.', 'ph_response' => 'اكتب ردك على المرسل…',
        'respond_resolve' => 'الرد والحل', 'reply_only' => 'رد (إبقاء مفتوحة)', 'escalate' => 'تصعيد',
        'print_pdf' => 'طباعة / PDF', 'generate' => 'إنشاء', 'period' => 'الفترة', 'avg_rating' => 'متوسط التقييم',
        'new_users' => 'مستخدمون جدد', 'logins' => 'عمليات الدخول', 'revenue_by_trip' => 'الإيرادات حسب الرحلة (المؤكدة)',
        'bookings_per_month' => 'الحجوزات المؤكدة شهرياً', 'amount' => 'المبلغ', 'ratings_by_trip' => 'التقييمات حسب الرحلة',
        'export_csv' => 'تصدير CSV', 'report_history' => 'التقارير المُنشأة',
        'exp_bookings' => 'الحجوزات', 'exp_payments' => 'المدفوعات', 'exp_complaints' => 'الشكاوى', 'exp_ratings' => 'التقييمات', 'exp_users' => 'المستخدمون',
        'maintenance' => 'الصيانة', 'maintenance_msg' => 'النظام قيد الصيانة. يرجى العودة لاحقاً.',
        'maintenance_help' => 'أثناء الصيانة، يستطيع المسؤولون فقط استخدام النظام؛ ويرى الآخرون إشعاراً.',
        'maintenance_off' => 'انتهت الصيانة — عاد النظام للعمل.', 'online' => 'يعمل',
        'notice_message' => 'نص الإشعار', 'start_maintenance' => 'بدء الصيانة', 'end_maintenance' => 'إنهاء الصيانة',
        'company_info' => 'معلومات الشركة', 'save' => 'حفظ', 'contact_messages' => 'رسائل التواصل',
        'audit_log' => 'سجل التدقيق', 'email_log' => 'الرسائل الصادرة',
        'email_log_help' => 'كل رسالة يرسلها النظام تُسجل هنا وفي بريد المستلم.',

        'edit_profile' => 'تعديل الملف', 'settings' => 'الإعدادات', 'change_photo' => 'تغيير صورة الملف',
        'stat_trips' => 'رحلات', 'stat_reviews' => 'تقييمات', 'favorites' => 'المفضلة',
        'member_since' => 'عضو منذ', 'tap_to_add_photo' => 'اضغط على الدائرة لإضافة صورة شخصية (اختياري).',
        'no_favorites' => 'لا توجد رحلات مفضلة بعد — اضغط ♡ على أي رحلة لحفظها هنا.',
        'add_favorite' => 'إضافة إلى المفضلة', 'remove_favorite' => 'إزالة من المفضلة',
        'saved_to_favorites' => 'تم الحفظ في المفضلة ♥', 'removed_from_favorites' => 'تمت الإزالة من المفضلة',
        'photo_updated' => 'تم تحديث الصورة الشخصية.', 'photo_removed' => 'تم حذف الصورة الشخصية.',
        'profile_photo' => 'الصورة الشخصية', 'profile_photo_hint' => 'اضغط على صورتك في الملف لتغييرها.',
        'remove_photo' => 'حذف الصورة', 'security' => 'كلمة المرور والأمان', 'security_hint' => 'تغيير كلمة المرور',
        'show_password' => 'إظهار كلمة المرور', 'update_password' => 'تحديث كلمة المرور',
        'rule_len' => '8 أحرف أو أكثر', 'rule_letter' => 'حرف', 'rule_digit' => 'رقم',
        'pw_weak' => 'ضعيفة', 'pw_medium' => 'متوسطة', 'pw_strong' => 'قوية', 'pw_match' => 'كلمتا المرور متطابقتان',
        'demo_restricted' => 'هذا حساب تجريبي عام: يمكنه فقط عرض البيانات التجريبية وتعديلها.',
        'demo_no_reset' => 'لا يمكن إعادة تعيين كلمة مرور الحسابات التجريبية. استخدم كلمة المرور المذكورة في README.',
        'reset_unavailable' => 'استعادة كلمة المرور عبر البريد غير متاحة حالياً. يرجى التواصل مع الشركة.',
        'code_not_sent' => 'تعذّر إرسال رمز الدخول بالبريد. حاول مرة أخرى لاحقاً.',
        'demo_domain_reserved' => 'هذا النطاق مخصص للحسابات التجريبية. يرجى استخدام بريدك الخاص.',
        'real_card_warning' => 'بوابة دفع تجريبية: لا يتم خصم أي مبلغ حقيقي. لا تُدخل بطاقة حقيقية — استخدم البطاقة التجريبية 4242 4242 4242 4242.',
        'demo_banner' => 'أنت تستخدم حساباً تجريبياً عاماً: ترى البيانات التجريبية فقط، وتعديل الحساب غير متاح.',
        'follow' => 'متابعة', 'following' => 'أتابعه', 'followers' => 'متابِع',
        'now_following' => 'أنت تتابع {name} — سيصلك إشعار برحلاته الجديدة.', 'unfollowed' => 'ألغيت متابعة {name}.',
        'no_following' => 'لا تتابع أي منظم رحلات بعد. تابع أحدهم لترى أحدث رحلاته هنا.',
        'find_organizers' => 'ابحث عن منظمين', 'new_from_following' => 'أحدث رحلات المنظمين الذين تتابعهم',
        'no_new_trips' => 'لا توجد رحلات قادمة منهم حالياً.', 'new' => 'جديد',
        'about_organizer' => 'معلومات', 'about_tab' => 'معلومات', 'verified_hint' => 'موثّق من الشركة',
        'n_upcoming' => '{n} رحلة قادمة', 'trips_summary' => '{n} منشورة · {u} قادمة',
        'private' => 'خاص بك', 'contact' => 'التواصل', 'contact_via_company' => 'تواصل مع المنظم عبر الشركة',
        'organizers_found' => 'منظمو الرحلات',

        'st_active' => 'نشط', 'st_pending' => 'معلّق', 'st_rejected' => 'مرفوض', 'st_suspended' => 'موقوف',
        'st_confirmed' => 'مؤكد', 'st_cancelled' => 'ملغى', 'st_paid' => 'مدفوع', 'st_failed' => 'فشل',
        'st_refunded' => 'مسترد', 'st_approved' => 'مقبول', 'st_hidden' => 'مخفي', 'st_published' => 'منشور',
        'st_draft' => 'مسودة', 'st_open' => 'مفتوحة', 'st_resolved' => 'محلولة', 'st_escalated' => 'مصعّدة', 'st_visible' => 'ظاهر',

        'help_tourists' => 'للسياح', 'help_organizers' => 'لمنظمي الرحلات', 'help_general' => 'عام',
        'help_more' => 'ما زلت بحاجة إلى مساعدة؟',
        'faq_t1_q' => 'كيف أنضم إلى جولة؟', 'faq_t1_a' => 'افتح الخريطة (أيقونة المنزل)، اضغط على دبوس أخضر ثم "انضم" — أو افتح رحلة واضغط "احجز الآن". أدخل اسمك ورقم هاتفك ولغتك، واختر عدد المقاعد وطريقة الدفع.',
        'faq_t2_q' => 'ما طرق الدفع المقبولة؟', 'faq_t2_a' => 'بطاقة ائتمان (يعالجها النظام المصرفي بأمان — لا يُحفظ رقم بطاقتك) أو نقداً. تُؤكد الحجوزات النقدية بعد أن يسجل المنظم دفعتك.',
        'faq_t3_q' => 'هل يمكنني إلغاء الحجز؟', 'faq_t3_a' => 'نعم. افتح الملف الشخصي › الجولات التي انضممت إليها واضغط إلغاء. يمكن إلغاء الحجوزات المؤكدة حتى يومين قبل الرحلة، وتُسترد مدفوعات البطاقة تلقائياً.',
        'faq_t4_q' => 'كيف أقيّم رحلة؟', 'faq_t4_a' => 'بعد انتهاء الرحلة، افتحها واختر من 1 إلى 5 نجوم مع تعليق اختياري. تُنشر التقييمات بعد المراجعة.',
        'faq_t5_q' => 'كيف أشارك الصور؟', 'faq_t5_a' => 'افتح الرحلة › ذكريات السفر واضغط "إضافة صورة". يمكن للمشاركين في الجولة فقط إضافة صور.',
        'faq_t6_q' => 'كيف أتنقل بين الصفحات على هاتفي؟', 'faq_t6_a' => 'استخدم الشريط السفلي (الملف، البريد، الرئيسية، البحث) أو اسحب يميناً أو يساراً.',
        'faq_o1_q' => 'كيف أصبح منظم رحلات؟', 'faq_o1_a' => 'سجّل كمنظم رحلات مع دراستك الجامعية وتدريبك ورخصك ومهاراتك. يتحقق المسؤول من معلوماتك ويصلك إشعار بالبريد.',
        'faq_o2_q' => 'كيف أنشئ رحلة؟', 'faq_o2_a' => 'رحلاتي › إنشاء رحلة. املأ التفاصيل، انقر على الخريطة لتحديد الموقع وأضف أماكن الجولة والفنادق والمطاعم.',
        'faq_o3_q' => 'هل هناك قواعد للخصومات؟', 'faq_o3_a' => 'يمكن أن يتراوح الخصم بين 0% و 50% من السعر الأساسي.',
        'faq_o4_q' => 'هل يمكنني حذف رحلة؟', 'faq_o4_a' => 'نعم إذا لم تكن لديها حجوزات نشطة. وإلا يجب أن يراجع المسؤول الحذف ويتجاوزه.',
        'faq_g1_q' => 'هل بياناتي آمنة؟', 'faq_g1_a' => 'كلمات المرور مشفرة، والوصول حسب الدور، ودخول المسؤول يتطلب رمزاً لمرة واحدة، وتُسجل كل الإجراءات الإدارية.',
        'faq_g2_q' => 'هل يمكنني استخدام التطبيق بالعربية؟', 'faq_g2_a' => 'نعم — استخدم زر عربي / EN أعلى كل صفحة.',
        'faq_g3_q' => 'نسيت كلمة المرور', 'faq_g3_a' => 'في صفحة الدخول اضغط "نسيت كلمة المرور؟" واتبع الرابط المرسل إلى بريدك.',
    ];
    return $d;
}
